### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [9]:
import numpy as np
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Accept two lists of 5 elements each from the user.
### Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [20]:
import numpy as np
n=[]
l=[]
for i in range(5):
    a=input()
    n.append(a)
for i in range(5):
    b=input()
    l.append(b)
p=np.array(n)
q=np.array(l)
o=np.concatenate((p,q))
print(o)
print(np.sort(o))

iewh
fejw
ei
eqjijew
eiji
ejioejdi
qwjdojed
qwii
iq3
j3eqj
['iewh' 'fejw' 'ei' 'eqjijew' 'eiji' 'ejioejdi' 'qwjdojed' 'qwii' 'iq3'
 'j3eqj']
['ei' 'eiji' 'ejioejdi' 'eqjijew' 'fejw' 'iewh' 'iq3' 'j3eqj' 'qwii'
 'qwjdojed']


### Write a code snippet to find the dimensions of a ndarray and its size.

In [41]:
import numpy as np
arr = np.array ([[ 1, 2, 3],
                 [ 4,4,5]] )
 
print("Dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

Dimensions:  2
Size of array:  6


### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [50]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a.shape)
b = a[np.newaxis, :]
print(b.shape)
c = np.expand_dims(a, axis=1)
print(c.shape)
(6, 1)

(5,)
(1, 5)
(5, 1)


(6, 1)

### Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [53]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]


### How to get unique items and counts of unique items?

In [57]:
a=np.array([12,13,13,13,12, 23, 23, 44, 54, 31])
(u, c) = np.unique(a, return_counts=True)
count = np.asarray((u,c))
print(count)

[[12 13 23 31 44 54]
 [ 2  3  2  1  1  1]]
